config/routes.rb
RailStrap::Application.routes.draw do

  root :to => "users#home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#login", :as => "log_in"
  post "auth" => "sessions#login"

  get "sign_up" => "users#new", :as => "sign_up"

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  def self.authenticate(email, password)

    user = User.is_a_valid_email(email) ? find_by_email(email) : find_by_username(email)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.auth_with_cookie(id)
    user = find_by_id(id)
    if user
      user
    else
      nil
    end
  end

  def self.is_a_valid_email(email)
    # Check the number of '@' signs.
    if email.count("@") != 1 then
      return false

    # We can now check the email using a simple regex.
    # You can replace the TLD's at the end with the TLD's you wish
    # to accept.
    elsif email =~ /^.*@.*(.com|.org|.net)$/ then
      return true
    else
      return false
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	helper_method :current_user
	before_filter :require_login

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_login
		unless logged_in?
			flash[:error] = "You must be logged in to access this section"
			redirect_to log_in_url
		end
	end


	# The logged_in? method simply returns true if the user is logged
	# in and false otherwise. It does this by "booleanizing" the
	# current_user method we created previously using a double ! operator.
	# Note that this is not common in Ruby and is discouraged unless you
	# really mean to convert something into true or false.
	def logged_in?
		!!current_user
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create, :login]
  def new
  end

  def login
    @user = User.new
    if logged_in?
      redirect_to root_url
    elsif !logged_in? && cookies.signed[:user_id]
      user = User.auth_with_cookie(cookies.signed[:user_id])
      session[:user_id] = cookies.signed[:user_id]
      redirect_to root_url, :notice => "Welcome back!"
    elsif request.post?
      user = User.authenticate(
        params.has_key?(:email) ? params[:email] : nil,
        params[:password])
      if user
        if params[:remember_me] == 'yes'
          cookies.permanent.signed[:user_id] = user.id
        end
        session[:user_id] = user.id
        redirect_to root_url, :notice => "Logged in!"
      else
        redirect_to root_url, :notice => "Invalid email or password"
      end
    else
      render "home"
    end
  end

  def destroy
    session[:user_id] = nil
    cookies.delete :user_id
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create, :home, :login]
  def new
    @user = User.new
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
      format.json{ render :json => @users }
    end
  end

  def show
    @user = User.find_by_id(params[:id])

    # If user not found
    if @user.nil?
      redirect_to users_path , :notice => "User not found"
    else
      respond_to do |format|
        format.html
        format.xml { render :xml  => @user }
        format.json{ render :json => @user }
      end
    end
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def home
    @user = User.new
    if current_user
      render "welcome"
    elsif cookies.signed[:user_id]
      redirect_to log_in_path
    else
      render "home"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user,
                      :notice => 'User updated')}
        format.json { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @user.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.id.to_s === params[:id].to_s
      redirect_to users_path, :notice => "You cant delete yourself !"
    else
      @user = User.find(params[:id])
      @user.delete

      respond_to do |format|
        format.html { redirect_to users_path, :notice => 'User deleted' }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!-- Consider specifying the language of your content by adding the `lang` attribute to <html> -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= RailStrap::Application.config.application_name %></title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag 'bootstrap.min.css' %>
    <%= stylesheet_link_tag 'style' %>


    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <%= javascript_include_tag 'modernizr-2.5.3.min.js' %>

    <%= csrf_meta_tag %>
</head>
<body>
    <!--[if lt IE 7]><p class="chromeframe">Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

    <div class="navbar navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to RailStrap::Application.config.application_name, root_path, :class => 'navbar-brand' %>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- Your nav here -->
          </ul>
          <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged as <%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Log out", log_out_path %></li>
              </ul>
            </li>
          </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="row">
        <div class="col-12">
          <% flash.each do |name, msg| %>
            <div class="alert alert-info">
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        </div>
      </div>

      <%= yield %>

      <hr>

      <footer>
        <p>&copy; <%= RailStrap::Application.config.application_name %> 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/assets/jquery.min.js" type="text/javascript"><\/script>')</script>

    <!-- scripts concatenated and minified via build script -->
    <%= javascript_include_tag 'jquery_ujs.js' %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
    <%= javascript_include_tag 'application.js' %>
    <!-- end scripts -->

    <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
         mathiasbynens.be/notes/async-analytics-snippet -->
    <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
</body>
</html>

app/views/users/_form.html.haml
= form_for @user, :html => {:class => ""} do |f|
  - if @user.errors.any?
    .alert.alert-danger.alert-block
      %h4 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %div.form-group
    = f.label :email
    = f.text_field :email, :placeholder => 'Email', :class => 'form-control'
  %div.form-group
    = f.label :username
    = f.text_field :username, :placeholder => 'Username', :class => 'form-control'
  %div.form-group
    = f.label :password
    = f.password_field :password, :placeholder => 'Password', :class => 'form-control'
  %div.form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, :placeholder => 'Password confirm', :class => 'form-control'
  %p.button= f.submit :class => 'btn btn-success', :value => 'Sign up'

app/views/users/edit.html.haml
%h2 Edit user
%hr
  = render 'form'

app/views/users/home.html.haml
.row
  .col-12.col-sm-12.col-lg-4.col-offset-4
    %h2.center= RailStrap::Application.config.application_name
    %hr
    .tabbable
      %ul.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#tab1"} Log in
        %li
          %a{"data-toggle" => "tab", :href => "#tab2"} Sign up
      .tab-content
        #tab1.tab-pane.active
          .panel
            = render "sessions/form"
        #tab2.tab-pane
          .panel
            = render :partial => "form", :locals => { :user => @user }

app/views/users/index.html.haml
%h2 Users
%hr
  %table.table.table-bordered
    %thead
      %tr
        %th #
        %th Email
        %th #
        %th #
        %th #
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td= user.email
          %td= link_to "Show", user
          %td= link_to "Edit", edit_user_path(user)
          %td= link_to "Delete", user, :confirm => "Are you sure?", :method => :delete

app/views/users/new.html.haml
.row
	.col-offset-4.col-4
		%h2 Sign Up
		%hr
			= render :partial => "form", :locals => { :user => @user }

app/views/users/show.html.haml
%h2 User
%hr
  Email: #{@user.email}

app/views/users/welcome.html.haml
.row
	.col-12
		%h3
			Hello #{current_user.email}
		%hr
		.panel
			%h4= link_to "Manage users", users_path